# Project: 棋类合集
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 棋类合集_private.res
OBJ      = main.o gobang.o go.o chchess.o chess.o football.o $(RES)
LINKOBJ  = main.o gobang.o go.o chchess.o chess.o football.o $(RES)
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -mwindows -leasyx
INCS     = 
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = 棋类合集.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

gobang.o: gobang.cpp
	$(CPP) -c gobang.cpp -o gobang.o $(CXXFLAGS)

go.o: go.cpp
	$(CPP) -c go.cpp -o go.o $(CXXFLAGS)

chchess.o: chchess.cpp
	$(CPP) -c chchess.cpp -o chchess.o $(CXXFLAGS)

chess.o: chess.cpp
	$(CPP) -c chess.cpp -o chess.o $(CXXFLAGS)

football.o: football.cpp
	$(CPP) -c football.cpp -o football.o $(CXXFLAGS)

棋类合集_private.res: 棋类合集_private.rc app.rc
	$(WINDRES) -i 棋类合集_private.rc --input-format=rc -o 棋类合集_private.res -O coff 

